### ISSUE TITLE
R.id.activity_tumblr_webview not found

### ISSUE THREAD

**Issue by EhsanAli18** [dakshsrivastava/Loglr#1]
Hello, I am not able to find R.id.activity_tumblr_webview in your projext. Kindly help me out

**Comment by ArcherN9** [comment]
@EhsanAli18 You closed the issue. I'm guessing you got it working?

**Comment by EhsanAli18** [comment]
@dakshsrivastava yes its working fine now. Can you please modify it for posting on tumblr too or suggest me something so that I can do it myself?

**Comment by ArcherN9** [comment]
@EhsanAli18 Jumblr does a great job at posting data to Tumblr and the API is very straight forward. This should help.
[Image posting Snippet](http://stackoverflow.com/questions/34436097/jumblr-api-gives-bad-request-while-posting-image-to-tumblr/34588227#34588227)
[](url)

**Comment by EhsanAli18** [comment]
But it's login is not as smooth as yours sir

**Comment by EhsanAli18** [comment]
Can I use the given code for posting? And please tell me how can I get blogname using your library?

**Comment by ArcherN9** [comment]
@EhsanAli18 Writing another wrapper for the Jumblr API doesn't really sound a novel idea. To extract Blogname, refer the README on [Jumblr Library](https://github.com/tumblr/jumblr).

Logically, Once you have the Consumer Key and Consumer Secret, set it in the Jumblr object & extract the User object by executing
 `User user = jumblrClient.user();`
Inside the user object, you'll  get blog names and other stuff.

**Comment by ArcherN9** [comment]
@EhsanAli18 have updated the library. I recommend using the new implementation. Overtime, the experience will become better as the library evolves.

**Comment by EhsanAli18** [comment]
Okay thanks a lot sir. I am now working on some other things. I will be back to work on Tumblr and will let you know if i face any problem. Once again thanks a lot sir.
