### ISSUE TITLE
 Failed to resolve: org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.0-beta-88

### ISSUE THREAD

**Issue by sttackk** [dakshsrivastava/Loglr#11]
After adding implementation 'com.daksh:loglr:2.1.3' to the app build.gradle file it gives the error Failed to resolve: org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.0-beta-88.

**Comment by ArcherN9** [comment]
Hey. That isn't nice. I guess jetBrains has moved on from Beta 88. I'll fall back to a more stable version. Thanks.

**Comment by ArcherN9** [comment]
Try with `implementation 'com.daksh:loglr:2.1.4'`.
