### ISSUE TITLE
How to get user name and email address?

### ISSUE THREAD

**Issue by AndroidTechvalens** [dakshsrivastava/Loglr#2]
Hello Developer,

Great work you have done!!
Can u please let me know how to fetch the user name and email address?

**Comment by ArcherN9** [comment]
Hey  @AndroidTechvalens. 
Refer [Jumblr Official Documentation](https://github.com/tumblr/jumblr). 

Post retrieving OAuthToken and OAuthSecretToken from Loglr, all you have to do to retrieve User details

```
// Create a new Jumblr client
JumblrClient client = new JumblrClient("CONSUMER KEY", "CONSUMER SECRET KEY");
client.setToken(
       strOAuthToken,     //Received from loginResult.getOAuthToken() method
       strOAuthTokenSecret //Received from loginResult.getOAuthTokenSecret() method
);
```

Once that's done, your JumblrClient may send and receive information from Tumblr.. To gain access to User's details, simply...

```
User user = client.user();
Log.i(TAG, user.getName()); 
```

Explore methods available in the User class. It'll return whatever information you require.

**Comment by AndroidTechvalens** [comment]
Hey,
Thanks for your response but this is JAVA library https://github.com/tumblr/jumblr and I need to add this in Android app.

Still not able to achieve this.

**Comment by AndroidTechvalens** [comment]
Any JAR file to import `JumblrClient class`

**Comment by ArcherN9** [comment]
Just use 

`compile 'com.tumblr:jumblr:0.0.11'`

**Comment by AndroidTechvalens** [comment]
Thanks Man,

It really help me  but i am getting below error - 

```
   org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.
                                                                 at org.scribe.model.Request.send(Request.java:69)
                                                                 at org.scribe.model.Request.send(Request.java:75)
                                                                 at com.tumblr.jumblr.request.RequestBuilder.get(RequestBuilder.java:92)
                                                                 at com.tumblr.jumblr.JumblrClient.user(JumblrClient.java:83)
```

**Comment by AndroidTechvalens** [comment]
Great work from your side.
All issues are resolved, many thanks for your help

**Comment by ArcherN9** [comment]
Glad bro.

**Comment by AndroidTechvalens** [comment]
Is it possible to get the email address?

**Comment by ArcherN9** [comment]
That depends on whether Jumblr Gives it away or not. I'm unsure.. you'll have to explore the `User` class in Jumblr.

**Comment by AndroidTechvalens** [comment]
Actually its not giving Email address, anyways thanks once again.

**Comment by mohitmanuja** [comment]
@dakshsrivastava  Hi, I used your library and I am trying to upload image and on Tumblr after successfull authentication I am getting this error:
                                                                     
  Caused by: com.tumblr.jumblr.exceptions.JumblrException: Unauthorized

This error is related to jumblr but it is happening due to token and secret. 
I verified my token from tumblr API user info site. If I am using that token it is working but If I am authenticating with your library I am getting this error although that token is not same as on API info site.

Please help.
