### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by mittalharsh54** [dakshsrivastava/Loglr#6]
How to get logout after logging in ?

**Comment by ArcherN9** [comment]
I looked up Tumblr's official documentation. It seems there is no provision to logout a user from APIs. The best you can do is delete the tokens you received. 

I'll see what I can do for this in the next build.

**Comment by ArcherN9** [comment]
No documentation of any logout API or invalidating auth tokens on Tumblr or Jumblr. Lost cause. Closing issue.
